//! Golden-vector tests for the binaryfuse module (VECTORS.md: `filters.json`).
//!
//! Each case builds a filter over `u64s(seed, n)` deduplicated and sorted (as
//! packstore does), serializes it as a packstore filter section, and checks
//! the BLAKE3 of the section (and the exact bytes for small n) against values
//! generated by the Go implementation.

mod common;

use amber_store_core::binaryfuse::BinaryFuse16;

#[derive(serde::Deserialize)]
struct FilterFile {
    cases: Vec<FilterCase>,
}

#[derive(serde::Deserialize)]
struct FilterCase {
    n: usize,
    seed: u64,
    section_blake3: String,
    section_hex: Option<String>,
}

#[test]
fn golden_filters() {
    let Some(raw) = common::load("filters.json") else {
        return;
    };
    let file: FilterFile = serde_json::from_slice(&raw).expect("parse filters.json");
    assert!(!file.cases.is_empty(), "filters.json has no cases");
    for case in &file.cases {
        let mut keys = common::u64s(case.seed, case.n);
        keys.sort_unstable();
        keys.dedup();
        let filter = BinaryFuse16::new(&keys)
            .unwrap_or_else(|e| panic!("n={} seed={}: build: {e}", case.n, case.seed));
        let section = filter.section_bytes();
        assert_eq!(
            blake3::hash(&section).to_hex().as_str(),
            case.section_blake3,
            "n={} seed={}: section BLAKE3",
            case.n,
            case.seed
        );
        if let Some(want_hex) = &case.section_hex {
            assert_eq!(
                &hex::encode(&section),
                want_hex,
                "n={} seed={}: section bytes",
                case.n,
                case.seed
            );
        }
        // The section must round-trip, and the parsed filter must find every
        // input key.
        let parsed = BinaryFuse16::parse_section(&section)
            .unwrap_or_else(|e| panic!("n={} seed={}: parse: {e}", case.n, case.seed));
        assert_eq!(
            parsed, filter,
            "n={} seed={}: round trip",
            case.n, case.seed
        );
        for &k in &keys {
            assert!(
                parsed.contains(k),
                "n={} seed={}: missing key {k:#x}",
                case.n,
                case.seed
            );
        }
    }
}
