//! Golden-vector test for the fstree codec: `tests/golden/fstree/` per
//! VECTORS.md, generated by the Go implementation.
//!
//! For every object in `objects.bin` the key is re-derived from the bytes
//! (BLAKE3 truncation + type/length consistency), and every structured
//! object round-trips decode → encode byte-identically.

mod common;

use std::collections::BTreeSet;

use amber_store_core::fstree;
use amber_store_core::key::{Key, Type};

#[derive(serde::Deserialize)]
struct Manifest {
    root: String,
    objects: Vec<ManifestObject>,
}

#[derive(serde::Deserialize)]
struct ManifestObject {
    key: String,
    size: u64,
}

struct GoldenObject {
    key: Key,
    bytes: Vec<u8>,
}

fn load_objects() -> Option<(Manifest, Vec<GoldenObject>)> {
    let manifest: Manifest =
        serde_json::from_slice(&common::load("fstree/manifest.json")?).expect("manifest parses");
    let bin = common::load("fstree/objects.bin")?;

    // objects.bin: key (32 bytes) ‖ big-endian u64 length ‖ object bytes.
    let mut objects = Vec::with_capacity(manifest.objects.len());
    let mut off = 0usize;
    while off < bin.len() {
        assert!(bin.len() - off >= 40, "truncated record header at {off}");
        let key = Key::parse(&bin[off..off + 32])
            .unwrap_or_else(|e| panic!("object {} key: {e}", objects.len()));
        let mut lenbuf = [0u8; 8];
        lenbuf.copy_from_slice(&bin[off + 32..off + 40]);
        let len = u64::from_be_bytes(lenbuf) as usize;
        off += 40;
        assert!(bin.len() - off >= len, "truncated object body at {off}");
        objects.push(GoldenObject {
            key,
            bytes: bin[off..off + len].to_vec(),
        });
        off += len;
    }
    assert_eq!(off, bin.len(), "trailing bytes in objects.bin");
    Some((manifest, objects))
}

#[test]
fn golden_fstree_objects() {
    let Some((manifest, objects)) = load_objects() else {
        return;
    };

    assert_eq!(objects.len(), 3444, "golden object count");
    assert_eq!(manifest.objects.len(), objects.len(), "manifest count");

    // The manifest is the deduplicated set of emitted objects, sorted by key
    // hex; objects.bin follows manifest order.
    let mut seen = BTreeSet::new();
    let mut prev: Option<String> = None;
    let mut type_counts = [0usize; 5];

    for (i, (m, o)) in manifest.objects.iter().zip(&objects).enumerate() {
        let key_hex = o.key.to_string();
        assert_eq!(m.key, key_hex, "object {i}: manifest key");
        assert_eq!(m.size, o.bytes.len() as u64, "object {i}: manifest size");
        assert!(seen.insert(key_hex.clone()), "object {i}: duplicate key");
        if let Some(p) = &prev {
            assert!(p < &key_hex, "object {i}: manifest not sorted by key hex");
        }
        prev = Some(key_hex);

        // The key's truncated hash must match a recomputed BLAKE3 of the
        // serialized bytes, whatever the type.
        let full = blake3::hash(&o.bytes);
        assert_eq!(
            o.key.hash(),
            &full.as_bytes()[..o.key.hash().len()],
            "object {i}: hash mismatch"
        );

        // Internal consistency of the type/length fields, plus a full
        // decode → re-encode byte comparison per type.
        let t = o.key.type_();
        type_counts[t as usize] += 1;
        match t {
            Type::Blob => {
                assert_eq!(
                    o.key.length(),
                    o.bytes.len() as u64,
                    "object {i}: Blob length"
                );
                let re = fstree::encode_blob(&o.bytes);
                assert_eq!(re.key, o.key, "object {i}: Blob re-encode key");
            }
            Type::FileNode => {
                let children = fstree::decode_file_node(&o.bytes)
                    .unwrap_or_else(|e| panic!("object {i}: FileNode decode: {e}"));
                let sum: u64 = children.iter().map(Key::length).sum();
                assert_eq!(
                    o.key.length(),
                    sum,
                    "object {i}: FileNode length = Σ children"
                );
                let re = fstree::encode_file_node(&children);
                assert_eq!(re.bytes, o.bytes, "object {i}: FileNode re-encode bytes");
                assert_eq!(re.key, o.key, "object {i}: FileNode re-encode key");
            }
            Type::DirLeaf => {
                let entries = fstree::decode_dir_leaf(&o.bytes)
                    .unwrap_or_else(|e| panic!("object {i}: DirLeaf decode: {e}"));
                let re = fstree::encode_dir_leaf(&entries)
                    .unwrap_or_else(|e| panic!("object {i}: DirLeaf re-encode: {e}"));
                assert_eq!(re.bytes, o.bytes, "object {i}: DirLeaf re-encode bytes");
                assert_eq!(re.key, o.key, "object {i}: DirLeaf re-encode key");
            }
            Type::DirNode => {
                let pairs = fstree::decode_dir_node(&o.bytes)
                    .unwrap_or_else(|e| panic!("object {i}: DirNode decode: {e}"));
                let re = fstree::encode_dir_node(&pairs)
                    .unwrap_or_else(|e| panic!("object {i}: DirNode re-encode: {e}"));
                assert_eq!(re.bytes, o.bytes, "object {i}: DirNode re-encode bytes");
                assert_eq!(re.key, o.key, "object {i}: DirNode re-encode key");
            }
            Type::XattrSet => {
                assert_eq!(
                    o.key.length(),
                    o.bytes.len() as u64,
                    "object {i}: XattrSet length"
                );
                let m = amber_store_core::cbor::decode_xattrs(&o.bytes)
                    .unwrap_or_else(|e| panic!("object {i}: XattrSet decode: {e}"));
                let re = fstree::encode_xattr_set(&m);
                assert_eq!(re.bytes, o.bytes, "object {i}: XattrSet re-encode bytes");
                assert_eq!(re.key, o.key, "object {i}: XattrSet re-encode key");
            }
        }
    }

    // The golden tree exercises every object type.
    for (t, n) in type_counts.iter().enumerate() {
        assert!(*n > 0, "no objects of type {t} in the golden tree");
    }

    // The root is a directory object present in the set.
    assert!(seen.contains(&manifest.root), "root key not in objects");
    let root = Key::parse(&hex::decode(&manifest.root).expect("root hex")).expect("root parses");
    assert!(
        matches!(root.type_(), Type::DirLeaf | Type::DirNode),
        "root must be a directory object, got {}",
        root.type_()
    );
}

#[test]
fn golden_fstree_dir_leaves_reference_known_objects() {
    // Cross-object consistency: every content/xattr key referenced by a
    // DirLeaf, every DirNode child, and every FileNode child resolves to an
    // object in the golden set with the matching type class.
    let Some((_, objects)) = load_objects() else {
        return;
    };
    let keys: BTreeSet<Key> = objects.iter().map(|o| o.key).collect();

    for (i, o) in objects.iter().enumerate() {
        match o.key.type_() {
            Type::FileNode => {
                for c in fstree::decode_file_node(&o.bytes).expect("decodes") {
                    assert!(keys.contains(&c), "object {i}: missing FileNode child {c}");
                    assert!(
                        matches!(c.type_(), Type::Blob | Type::FileNode),
                        "object {i}: FileNode child has type {}",
                        c.type_()
                    );
                }
            }
            Type::DirLeaf => {
                for e in fstree::decode_dir_leaf(&o.bytes).expect("decodes") {
                    if !e.content_key.is_empty() {
                        let c = Key::parse(&e.content_key).expect("content key parses");
                        assert!(keys.contains(&c), "object {i}: missing content {c}");
                    }
                    if !e.xattrs_key.is_empty() {
                        let x = Key::parse(&e.xattrs_key).expect("xattrs key parses");
                        assert_eq!(x.type_(), Type::XattrSet, "object {i}: xattrs key type");
                        assert!(keys.contains(&x), "object {i}: missing xattr set {x}");
                    }
                }
            }
            Type::DirNode => {
                for p in fstree::decode_dir_node(&o.bytes).expect("decodes") {
                    let c = Key::parse(&p.child_key).expect("child key parses");
                    assert!(
                        matches!(c.type_(), Type::DirLeaf | Type::DirNode),
                        "object {i}: DirNode child has type {}",
                        c.type_()
                    );
                    assert!(keys.contains(&c), "object {i}: missing DirNode child {c}");
                }
            }
            _ => {}
        }
    }
}
