//! Golden-vector tests for the `amberpack` module: `tests/golden/amberpack/`
//! per VECTORS.md, generated by the Go implementation.

mod common;

use std::collections::HashMap;

use amber_store_core::amberpack::{
    REC_HEADER_SIZE, Reader, Writer, decode_payload, encode_record, parse_record,
};
use amber_store_core::key::Key;

#[derive(serde::Deserialize)]
struct RawFile {
    cases: Vec<RawCase>,
}

#[derive(serde::Deserialize)]
struct RawCase {
    key: String,
    payload: common::Payload,
    record_blake3: String,
    /// Present only for payloads <= 256 bytes.
    record_hex: Option<String>,
}

#[derive(serde::Deserialize)]
struct CompressedFile {
    cases: Vec<CompressedCase>,
}

#[derive(serde::Deserialize)]
struct CompressedCase {
    record_hex: String,
    key: String,
    payload: common::Payload,
}

fn parse_key(hex_key: &str, ctx: &str) -> Key {
    let raw = hex::decode(hex_key).unwrap_or_else(|e| panic!("{ctx}: bad key hex: {e}"));
    Key::parse(&raw).unwrap_or_else(|e| panic!("{ctx}: key parse: {e}"))
}

/// Parses `fstree/objects.bin`: for each object in manifest order,
/// `key (32 bytes) ‖ big-endian u64 byte length ‖ object bytes`.
fn parse_objects_bin(b: &[u8]) -> Vec<(Key, Vec<u8>)> {
    let mut out = Vec::new();
    let mut off = 0usize;
    while off < b.len() {
        assert!(off + 40 <= b.len(), "objects.bin: truncated entry at {off}");
        let k = Key::parse(&b[off..off + 32]).expect("objects.bin: bad key");
        let len = u64::from_be_bytes(b[off + 32..off + 40].try_into().unwrap()) as usize;
        off += 40;
        assert!(
            off + len <= b.len(),
            "objects.bin: truncated object at {off}"
        );
        out.push((k, b[off..off + len].to_vec()));
        off += len;
    }
    out
}

/// Rust encode(key, payload) byte-equals the Go record for incompressible
/// payloads (flag 0), and the same bytes parse and round-trip.
#[test]
fn golden_records_raw() {
    let Some(bytes) = common::load("amberpack/records_raw.json") else {
        return;
    };
    let file: RawFile = serde_json::from_slice(&bytes).expect("records_raw.json parses");
    assert!(!file.cases.is_empty(), "records_raw.json has no cases");

    for (i, c) in file.cases.iter().enumerate() {
        let k = parse_key(&c.key, &format!("case {i}"));
        let payload = c.payload.bytes();

        // Encode: must stay raw (flag 0) and byte-match the Go record.
        let rec = encode_record(k, &payload).unwrap_or_else(|e| panic!("case {i}: encode: {e}"));
        assert_eq!(rec[33], 0, "case {i}: raw payload must keep flag 0");
        assert_eq!(
            blake3::hash(&rec).to_hex().as_str(),
            c.record_blake3,
            "case {i}: record bytes differ from Go (blake3)"
        );
        if let Some(record_hex) = &c.record_hex {
            assert_eq!(
                hex::encode(&rec),
                *record_hex,
                "case {i}: record bytes differ from Go"
            );
        }

        // Parse the same bytes: header fields and payload round-trip.
        let r = parse_record(&rec).unwrap_or_else(|e| panic!("case {i}: parse: {e}"));
        assert_eq!(r.key, k, "case {i}: parsed key");
        assert_eq!(r.flags, 0, "case {i}: parsed flags");
        assert_eq!(r.ulen as usize, payload.len(), "case {i}: ulen");
        assert_eq!(r.slen, r.ulen, "case {i}: raw slen == ulen");
        let got = decode_payload(r.flags, r.ulen, &rec[REC_HEADER_SIZE..])
            .unwrap_or_else(|e| panic!("case {i}: decode: {e}"));
        assert_eq!(got, payload, "case {i}: payload round-trip");
    }
}

/// Go-encoded compressed records: parse + decode recovers the payload exactly.
/// A Rust re-encode is NOT byte-compared (zstd frames differ between
/// libzstd and Go's klauspost), but it must round-trip through the Rust
/// parser and set flag 1 for these payloads.
#[test]
fn golden_records_compressed() {
    let Some(bytes) = common::load("amberpack/records_compressed.json") else {
        return;
    };
    let file: CompressedFile =
        serde_json::from_slice(&bytes).expect("records_compressed.json parses");
    assert!(
        !file.cases.is_empty(),
        "records_compressed.json has no cases"
    );

    for (i, c) in file.cases.iter().enumerate() {
        let k = parse_key(&c.key, &format!("case {i}"));
        let payload = c.payload.bytes();
        let rec = hex::decode(&c.record_hex).unwrap_or_else(|e| panic!("case {i}: hex: {e}"));

        // Decode the Go record.
        let r = parse_record(&rec).unwrap_or_else(|e| panic!("case {i}: parse Go record: {e}"));
        assert_eq!(r.key, k, "case {i}: key");
        assert_eq!(r.flags, 1, "case {i}: Go record must carry the zstd flag");
        assert_eq!(r.ulen as usize, payload.len(), "case {i}: ulen");
        assert!(r.slen < r.ulen, "case {i}: compressed slen < ulen");
        assert_eq!(
            rec.len(),
            REC_HEADER_SIZE + r.slen as usize,
            "case {i}: record length"
        );
        let got = decode_payload(r.flags, r.ulen, &rec[REC_HEADER_SIZE..])
            .unwrap_or_else(|e| panic!("case {i}: decode Go payload: {e}"));
        assert_eq!(got, payload, "case {i}: Go payload round-trip");

        // Rust re-encode: compresses too (flag 1) and round-trips.
        let enc = encode_record(k, &payload).unwrap_or_else(|e| panic!("case {i}: encode: {e}"));
        assert_eq!(enc[33], 1, "case {i}: Rust encoder must set the zstd flag");
        let r2 = parse_record(&enc).unwrap_or_else(|e| panic!("case {i}: parse own record: {e}"));
        assert_eq!(r2.key, k, "case {i}: own key");
        assert_eq!(r2.flags, 1, "case {i}: own flags");
        let got2 = decode_payload(r2.flags, r2.ulen, &enc[REC_HEADER_SIZE..])
            .unwrap_or_else(|e| panic!("case {i}: decode own payload: {e}"));
        assert_eq!(got2, payload, "case {i}: own payload round-trip");
    }
}

/// Stream-decode the Go-written pack of every golden fstree object; the
/// resulting key -> payload map must equal the golden objects
/// (`fstree/objects.bin` is the ground truth) and the end marker must be
/// observed.
#[test]
fn golden_pack_go() {
    let Some(pack) = common::load("amberpack/pack_go.bin") else {
        return;
    };
    let Some(objects_bin) = common::load("fstree/objects.bin") else {
        return;
    };
    let want = parse_objects_bin(&objects_bin);
    assert!(!want.is_empty(), "fstree/objects.bin has no objects");

    let mut reader = Reader::new(&pack[..]);
    let mut got: Vec<(Key, Vec<u8>)> = Vec::new();
    for item in reader.by_ref() {
        got.push(item.expect("pack_go.bin must stream-decode cleanly"));
    }
    // The iterator finished without an error item: the end marker was
    // observed (truncation would have surfaced as Malformed).
    assert!(
        reader.next().is_none(),
        "reader must be fused after the end"
    );

    assert_eq!(got.len(), want.len(), "object count");
    let want_map: HashMap<Key, Vec<u8>> = want.into_iter().collect();
    let got_map: HashMap<Key, Vec<u8>> = got.into_iter().collect();
    assert_eq!(
        got_map.len(),
        want_map.len(),
        "duplicate keys in decoded pack"
    );
    for (k, p) in &want_map {
        let g = got_map
            .get(k)
            .unwrap_or_else(|| panic!("pack is missing object {k}"));
        assert_eq!(g, p, "payload mismatch for {k}");
    }
}

/// `pack_empty.bin` (magic + end marker only) decodes to zero records.
#[test]
fn golden_pack_empty() {
    let Some(pack) = common::load("amberpack/pack_empty.bin") else {
        return;
    };
    let mut n = 0;
    for item in Reader::new(&pack[..]) {
        item.expect("pack_empty.bin must decode cleanly");
        n += 1;
    }
    assert_eq!(n, 0, "empty pack must contain zero records");
}

/// Write all golden objects with the Rust writer, re-read with the Rust
/// reader: same sequence.
#[test]
fn golden_pack_round_trip() {
    let Some(objects_bin) = common::load("fstree/objects.bin") else {
        return;
    };
    let objs = parse_objects_bin(&objects_bin);
    assert!(!objs.is_empty(), "fstree/objects.bin has no objects");

    let mut w = Writer::new(Vec::new());
    for (k, p) in &objs {
        w.add(*k, p).unwrap_or_else(|e| panic!("add {k}: {e}"));
    }
    let buf = w.finish().expect("finish");

    let mut got: Vec<(Key, Vec<u8>)> = Vec::new();
    for item in Reader::new(&buf[..]) {
        got.push(item.expect("own pack must decode cleanly"));
    }
    assert_eq!(got.len(), objs.len(), "object count");
    assert_eq!(got, objs, "round-tripped objects differ");
}
