//! Golden-vector test for the `amberignore` module:
//! `tests/golden/amberignore.json` per VECTORS.md, generated by the Go
//! implementation.
//!
//! Each case materializes its `.amberignore` files into a temporary tree and
//! then evaluates every check the way ingest does: matchers descend per
//! directory, and a directory that is ignored prunes its whole subtree (a
//! `!` re-include below an excluded directory has no effect, matching
//! gitignore's walk behavior — see the `no-reinclude-under-ignored-dir`
//! vector).

mod common;

use std::fs;

use amber_store_core::amberignore::{FILE_NAME, Matcher};

#[derive(serde::Deserialize)]
struct VectorsFile {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    files: Vec<IgnoreFile>,
    checks: Vec<Check>,
}

#[derive(serde::Deserialize)]
struct IgnoreFile {
    /// Directory containing the `.amberignore`, relative to the scan root
    /// (`""` = root).
    dir: String,
    lines: Vec<String>,
}

#[derive(serde::Deserialize)]
struct Check {
    /// `/`-separated path relative to the scan root.
    path: String,
    is_dir: bool,
    ignored: bool,
}

#[test]
fn golden_amberignore() {
    let Some(bytes) = common::load("amberignore.json") else {
        return;
    };
    let file: VectorsFile = serde_json::from_slice(&bytes).expect("amberignore.json parses");
    assert!(!file.cases.is_empty(), "amberignore.json has no cases");

    for case in &file.cases {
        let tmp = tempfile::tempdir().expect("tempdir");
        for f in &case.files {
            let dir = if f.dir.is_empty() {
                tmp.path().to_path_buf()
            } else {
                tmp.path().join(&f.dir)
            };
            fs::create_dir_all(&dir).expect("create ignore-file directory");
            let mut content = f.lines.join("\n");
            content.push('\n');
            fs::write(dir.join(FILE_NAME), content).expect("write .amberignore");
        }

        for check in &case.checks {
            let got = evaluate(tmp.path(), &check.path, check.is_dir);
            assert_eq!(
                got, check.ignored,
                "case {:?}: path {:?} is_dir={}",
                case.name, check.path, check.is_dir
            );
        }
    }
}

/// Evaluates one check the way a filtered ingest of `root` would: descend a
/// matcher along the path's parent directories, pruning as soon as any parent
/// directory is ignored, then ask about the final component with `is_dir`.
fn evaluate(root: &std::path::Path, path: &str, is_dir: bool) -> bool {
    let comps: Vec<&str> = path.split('/').collect();
    let mut m = Matcher::root(root).expect("root matcher");
    let mut abs = root.to_path_buf();
    for (i, comp) in comps.iter().enumerate() {
        if i == comps.len() - 1 {
            return m.ignored(comp.as_bytes(), is_dir);
        }
        // Parent components are directories; an ignored directory prunes the
        // whole subtree.
        if m.ignored(comp.as_bytes(), true) {
            return true;
        }
        abs = abs.join(comp);
        m = m.descend(&abs, comp.as_bytes()).expect("descend");
    }
    unreachable!("path has at least one component");
}
