//! Golden-vector test for the `key` module: `tests/golden/keys.json` per
//! VECTORS.md, generated by the Go implementation.

mod common;

use amber_store_core::key::{Key, Type};

#[derive(serde::Deserialize)]
struct KeysFile {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    #[serde(rename = "type")]
    type_: u8,
    /// Decimal string; may exceed 2^53 (JSON-safe integer range).
    length: String,
    payload: common::Payload,
    /// 64 lowercase hex chars.
    key: String,
}

#[test]
fn golden_keys() {
    let Some(bytes) = common::load("keys.json") else {
        return;
    };
    let file: KeysFile = serde_json::from_slice(&bytes).expect("keys.json parses");
    assert!(!file.cases.is_empty(), "keys.json has no cases");

    for (i, c) in file.cases.iter().enumerate() {
        let t =
            Type::from_u8(c.type_).unwrap_or_else(|| panic!("case {i}: invalid type {}", c.type_));
        let length = common::parse_u64(&c.length);
        let payload = c.payload.bytes();

        // The vector key is key.New(type, length, data(payload)).
        let k = Key::new(t, length, &payload);
        assert_eq!(
            k.to_string(),
            c.key,
            "case {i}: type {t} length {length} payload {} bytes",
            payload.len()
        );

        // The golden key must round-trip through parse and be canonical, and
        // the accessors must recover the inputs.
        let raw = hex::decode(&c.key).unwrap_or_else(|e| panic!("case {i}: bad key hex: {e}"));
        let parsed = Key::parse(&raw).unwrap_or_else(|e| panic!("case {i}: parse: {e}"));
        assert_eq!(parsed, k, "case {i}: parsed key differs");
        assert_eq!(parsed.type_(), t, "case {i}: type accessor");
        assert_eq!(parsed.length(), length, "case {i}: length accessor");
        assert_eq!(
            parsed.hash(),
            &blake3::hash(&payload).as_bytes()[..parsed.hash().len()],
            "case {i}: hash truncation"
        );
    }
}
