//! Golden-vector test for the `reference` module: `tests/golden/reference.json`
//! per VECTORS.md, generated by the Go implementation.

mod common;

use amber_store_core::reference::Reference;

#[derive(serde::Deserialize)]
struct RefFile {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    /// 64 lowercase hex chars.
    key: String,
    user: String,
    /// Decimal i64 string (ns since the Unix epoch).
    created_at: String,
    #[serde(default)]
    signature_hex: Option<String>,
    #[serde(default)]
    public_key_hex: Option<String>,
    /// The canonical encoding.
    bytes_hex: String,
}

fn opt_hex(field: &Option<String>, what: &str, i: usize) -> Vec<u8> {
    match field {
        Some(h) => hex::decode(h).unwrap_or_else(|e| panic!("case {i}: bad {what} hex: {e}")),
        None => Vec::new(),
    }
}

#[test]
fn golden_reference() {
    let Some(bytes) = common::load("reference.json") else {
        return;
    };
    let file: RefFile = serde_json::from_slice(&bytes).expect("reference.json parses");
    assert!(!file.cases.is_empty(), "reference.json has no cases");

    for (i, c) in file.cases.iter().enumerate() {
        let r = Reference {
            name: c.name.clone(),
            key: hex::decode(&c.key).unwrap_or_else(|e| panic!("case {i}: bad key hex: {e}")),
            user: c.user.clone(),
            created_at: common::parse_i64(&c.created_at),
            signature: opt_hex(&c.signature_hex, "signature", i),
            public_key: opt_hex(&c.public_key_hex, "public key", i),
        };
        let want =
            hex::decode(&c.bytes_hex).unwrap_or_else(|e| panic!("case {i}: bad bytes hex: {e}"));

        // Encode must byte-match the Go encoding.
        let enc = r
            .encode()
            .unwrap_or_else(|e| panic!("case {i} ({:?}): encode: {e}", c.name));
        assert_eq!(
            hex::encode(&enc),
            c.bytes_hex,
            "case {i} ({:?}): encoding differs",
            c.name
        );

        // Decode must accept the canonical bytes and recover every field.
        let dec = Reference::decode(&want)
            .unwrap_or_else(|e| panic!("case {i} ({:?}): decode: {e}", c.name));
        assert_eq!(dec, r, "case {i} ({:?}): decoded fields differ", c.name);
    }
}
